"""Metric definitions shown next to every metric in the UI and exports."""

METRIC_DEFINITIONS = {
    "exposed_population": {"label": "Estimated population in potentially affected zones", "unit": "people",
        "better": "lower", "definition": "Sum over zones of population x share of the zone's area covered by hazard zones at or above the Watch flood-risk level. A modeled estimate, not confirmed flooding."},
    "vulnerability_weighted_exposure": {"label": "Vulnerability-weighted exposure", "unit": "person-equivalents",
        "better": "lower", "definition": "Exposed population x zone vulnerability weight x mobility-constraint factor."},
    "pop_reduced_hospital": {"label": "Population with reduced hospital accessibility", "unit": "people", "better": "lower",
        "definition": "Population of zones whose best operating hospital is unreachable, beyond 20 min, or >=25% and >=2 min slower than baseline. Each zone counted once."},
    "pop_reduced_shelter": {"label": "Population with reduced shelter accessibility", "unit": "people", "better": "lower",
        "definition": "As above for shelters (25 min threshold)."},
    "pop_reduced_water": {"label": "Population with reduced water-point accessibility", "unit": "people", "better": "lower",
        "definition": "As above for water distribution points (15 min threshold)."},
    "pop_reduced_any": {"label": "Population with reduced access to any essential service", "unit": "people", "better": "lower",
        "definition": "Union over hospital/shelter/water: a zone's population is counted once even if several services are reduced."},
    "roads_affected": {"label": "Roads affected", "unit": "segments", "better": "lower",
        "definition": "Road segments that are degraded, restricted or closed."},
    "roads_closed": {"label": "Roads closed", "unit": "segments", "better": "lower",
        "definition": "Segments excluded from routing (flood impassable or explicitly closed)."},
    "facilities_operationally_affected": {"label": "Operationally affected facilities", "unit": "facilities", "better": "lower",
        "definition": "Facilities with capacity below normal (power or explicit failure). Independent of whether roads reach them."},
    "facilities_inaccessible_some_zone": {"label": "Facilities inaccessible from at least one zone", "unit": "facilities", "better": "lower",
        "definition": "Facilities that were reachable within their threshold from a zone at baseline but are not under this scenario."},
    "avg_hospital_time_min": {"label": "Average modeled travel time to hospitals", "unit": "min", "better": "lower",
        "definition": "Population-weighted mean of each zone's best time to an operating hospital; zones with no route are excluded and reported separately."},
    "zones_no_feasible_route": {"label": "Zones with no feasible route to a service", "unit": "zones", "better": "lower",
        "definition": "Zones with no operating hospital, shelter or water point reachable within its threshold."},
    "service_capacity_available": {"label": "Essential-service capacity available", "unit": "capacity units", "better": "higher",
        "definition": "Sum of capacity x operational multiplier for hospitals, shelters and water points reachable within threshold from at least one zone."},
    "shelter_capacity_available": {"label": "Shelter capacity available", "unit": "people", "better": "higher",
        "definition": "Capacity x operational multiplier of reachable shelters."},
    "shelter_demand": {"label": "Estimated shelter demand", "unit": "people", "better": "lower",
        "definition": "15% of vulnerability-weighted exposure (illustrative displacement assumption)."},
    "shelter_shortfall": {"label": "Shelter shortfall", "unit": "people", "better": "lower",
        "definition": "max(0, estimated demand - available shelter capacity)."},
    "hospitals_accessible": {"label": "Hospitals reachable from affected areas", "unit": "facilities", "better": "higher",
        "definition": "Operating hospitals reachable within 20 min from at least one zone."},
    "shelters_accessible": {"label": "Shelters reachable", "unit": "facilities", "better": "higher",
        "definition": "Operating shelters reachable within 25 min from at least one zone."},
    "water_points_accessible": {"label": "Water points reachable", "unit": "facilities", "better": "higher",
        "definition": "Operating water points reachable within 15 min from at least one zone."},
    "electricity_dependent_affected": {"label": "Electricity-dependent facilities affected", "unit": "facilities", "better": "lower",
        "definition": "Power-dependent facilities whose power node failed and that run below normal capacity."},
    "resources_deployed": {"label": "Resources deployed", "unit": "units", "better": "neutral",
        "definition": "Number of response interventions applied to the recovery run."},
    "budget_consumed": {"label": "Budget consumed", "unit": "INR lakh (illustrative)", "better": "neutral",
        "definition": "Sum of deployment and repair costs of deployed interventions."},
    "population_access_restored": {"label": "Modeled population access restored", "unit": "person-service equivalents", "better": "higher",
        "definition": "Sum over zones of population x (reduced services in disaster - reduced services in recovery) / 3, floored at 0."},
}

ASSUMPTIONS = [
    "All geography, populations, facilities and infrastructure are SYNTHETIC illustrative data for a fictional district.",
    "The flood model is a transparent conceptual index for comparative planning; it is not calibrated and is not a flood forecast.",
    "Flood risk = rainfall intensity factor x susceptibility x (1 - drainage effectiveness) x exposure factor x gain (clamped 0..1).",
    "Road states: Watch -> degraded (x1.4 time), Flood risk -> restricted (x3.0 time), Impassable or explicit closure -> closed (removed from routing).",
    "Travel times use shortest paths on the road graph (Dijkstra); straight-line distance is never used for accessibility.",
    "Power is a simplified dependency model (facility -> power node). Substations fail when flood risk is Impassable or when selected.",
    "Backup power: 60% capacity within rated hours, 25% once exhausted; portable generators restore 85%.",
    "Shelter demand assumes 15% of vulnerability-weighted exposure seeks shelter.",
    "Response times are deployment time plus modeled travel from the staging depot on the disaster-state road network.",
    "Recovery metrics come from re-running the same deterministic engine with interventions applied.",
]
